/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gui.settings.ActionSettings;
import javax.swing.JOptionPane;

/**
 *
 * @author Bugrahan
 */
public class ProfilPage extends javax.swing.JFrame {

    /**
     * Creates new form ProfilPage
     */
    public ProfilPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        profilPanel.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        phoneInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        passwordInput = new javax.swing.JPasswordField();
        updatePhoneButton = new javax.swing.JButton();
        updatePasswordButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Telefon Numarası:");

        phoneInput.setEnabled(false);

        jLabel4.setText("Şifre:");

        backButton.setText("Geri");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        passwordInput.setEnabled(false);

        updatePhoneButton.setText("Edit");
        updatePhoneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatePhoneButtonMouseClicked(evt);
            }
        });
        updatePhoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePhoneButtonActionPerformed(evt);
            }
        });

        updatePasswordButton.setText("Edit");
        updatePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilPanelLayout = new javax.swing.GroupLayout(profilPanel);
        profilPanel.setLayout(profilPanelLayout);
        profilPanelLayout.setHorizontalGroup(
            profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilPanelLayout.createSequentialGroup()
                .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(phoneInput))
                        .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profilPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(updatePhoneButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(updatePasswordButton)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        profilPanelLayout.setVerticalGroup(
            profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(92, 92, 92)
                .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(phoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePhoneButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePasswordButton))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ActionSettings.setVisible(this, new HomePage());
    }//GEN-LAST:event_backButtonActionPerformed

    private void updatePhoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePhoneButtonActionPerformed
        
    }//GEN-LAST:event_updatePhoneButtonActionPerformed
    
    private int clickPasswordCounter = 0;
    private void updatePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePasswordButtonActionPerformed
        if(this.clickPasswordCounter == 0){
            passwordInput.setEnabled(true);
            updatePasswordButton.setText("Save");
            clickPasswordCounter++;
        }else{
            passwordInput.setEnabled(false);
            updatePasswordButton.setText("Edit");
            JOptionPane.showMessageDialog(this, "Şifre Güncellendi!");
            clickPasswordCounter = 0;
        }
    }//GEN-LAST:event_updatePasswordButtonActionPerformed
    
    private int clickPhoneCounter = 0;
    private void updatePhoneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePhoneButtonMouseClicked
        if(this.clickPhoneCounter == 0){
            phoneInput.setEnabled(true);
            updatePhoneButton.setText("Save");
            clickPhoneCounter++;
        }else{
            phoneInput.setEnabled(false);
            updatePhoneButton.setText("Edit");
            JOptionPane.showMessageDialog(this, "Telefon Numarası Güncellendi!");
            clickPhoneCounter = 0;
        }
        
    }//GEN-LAST:event_updatePhoneButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JPanel profilPanel;
    private javax.swing.JButton updatePasswordButton;
    private javax.swing.JButton updatePhoneButton;
    // End of variables declaration//GEN-END:variables
}
